"""adding expires column

Revision ID: 6b77d83d55a8
Revises: 32084eb082ce
Create Date: 2017-11-28 20:19:15.814556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b77d83d55a8'
down_revision = '32084eb082ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snacks', sa.Column('expires', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snacks', 'expires')
    # ### end Alembic commands ###
